### ISSUE TITLE
[from v3] If gas price in MetaMask doesn't match gas price in header of MyEtherWallet, cannot use "send total avail balance" button

### ISSUE THREAD

**Issue by tayvano** [MyEtherWallet/MyEtherWallet#269] opened 2017-10-06 08:32 UTC
Another one where I'm not sure if it's still an issue in v4.

Video of the issue can be seen here:

https://youtu.be/9t8IkLU0R6Y

Original report: 

https://twitter.com/cryptotraveler/status/915995294378143744

**Comment by tayvano** [comment] 2017-10-06 08:32
Is there a "not a v4 blocker" label?

**Comment by wbobeirne** [comment] 2017-10-06 18:16
We can assume as much if it's not labeled "Blocking v4 Full Launch", doubly so with the low priority label.

**Comment by wbobeirne** [comment] 2018-01-02 05:48
The video linked above actually shows that the transaction fee was over priced [because of the gas **limit**, not the gas price](https://youtu.be/9t8IkLU0R6Y?t=45). I'm not sure how it would have changed from 21000 to 31501, but something seems pretty wrong with that.

**Comment by dternyak** [comment] 2018-01-15 10:22
Can't reproduce on V4 - closing for now.

**Closed by dternyak** 2018-01-15 10:22 UTC
Labels: 0_issue: low, 2_gas
