### ISSUE TITLE
[BUG] CLOSE_NOTIFICATION doesn't seem to work

### ISSUE THREAD

**Issue by eddiewang** [MyEtherWallet/MyEtherWallet#698] opened 2017-12-31 20:32 UTC
The new show notification component does not seem to close. I confirmed that the reducer is indeed removing it from the redux state, and the props being passed into the Notification component shouldn't technically be there anymore, but for some reason the component stays there.
![2017-12-31 14 31 10](https://user-images.githubusercontent.com/2057997/34464090-6a65518e-ee37-11e7-99f6-188a854dde4b.gif)

**Comment by dternyak** [comment] 2018-01-01 00:44
Duplicate of https://github.com/MyEtherWallet/MyEtherWallet/issues/645

**Closed** 2018-01-01 00:50 UTC
