### ISSUE TITLE
Clone the repo does not work

### ISSUE THREAD

**Issue by T-Shilov** [MyEtherWallet/MyEtherWallet#3792] opened 2022-04-21 18:17 UTC
###### Info

- **Version**: 6.5.2-hotfix.1
- **Browser**: Firefox 91.8.0esr/64
- **OS**: Linux Debian 10.12  / 64 bit

###### Steps to reproduce

Chapter **Getting started**, item 2:

Run commands:  `git clone git@github.com:MyEtherWallet/MyEtherWallet.git`

###### What happens instead?
Occurs errors:

> Cloning in "MyEtherWallet"…
> Warning: Permanently added the ECDSA host key for IP address '140.82.121.3' to the list of known hosts.
> git@github.com: Permission denied (publickey).
> fatal: Could not read from an external repository.

**Comment by henryclw** [comment] 2022-04-27 05:34
If you try to clone other repo in GitHub, will this same error occurs?

**Comment by T-Shilov** [comment] 2022-04-27 07:46
Use another repo? And how to do it?

**Comment by henryclw** [comment] 2022-04-28 05:31
> Use another repo? And how to do it?

I guess the problem is your connection with GitHub, not this GitHub repo.

What happens if you try

```bash
git clone git@github.com:nextcloud/docker.git
```

P.S. this is what I mean by another repo

**Comment by gamalielhere** [comment] 2023-05-17 18:27
Closing as this isn't a MEW issue

**Closed by gamalielhere** 2023-05-17 18:27 UTC
