### ISSUE TITLE
Customize Tx fee issue

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#399] opened 2019-01-09 21:25 UTC
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

![image](https://user-images.githubusercontent.com/31494364/50929085-3b18ee80-1411-11e9-8968-ce2d7a04952d.png)

- **Bug Request**

Can not enter a correct number

**Comment by kvhnuke** [comment] 2019-01-09 21:52
I believe this is fixed in a7dd9e459a492724c6c9d2bda96d6eab17cf20ab
can you please check https://www.mewbuilds.com/build/f8e6309367e892ba302ad3604760e13d48755bec/index.html and see whether the issue is still there

**Comment by jackhuangusa** [comment] 2019-01-09 22:34
@kvhnuke Not yet :(
<img width="511" alt="screen shot 2019-01-09 at 2 32 50 pm" src="https://user-images.githubusercontent.com/31494364/50932828-9cde5600-141b-11e9-9011-5b82d365f782.png">

**Closed as completed** 2019-01-10 01:23 UTC
Labels: Fixed
