### ISSUE TITLE
MyEtherWallet-v6.9.8-Offline.zip  index doesn't work correctly

### ISSUE THREAD

**Issue by AlbertoIT1** [MyEtherWallet/MyEtherWallet#4948] opened 2024-06-21 15:29 UTC
I just downloaded the zip file  MyEtherWallet-v6.9.8-Offline.zip  on https://github.com/MyEtherWallet/MyEtherWallet/releases. 
The problem is, when I unzip the file and open it offline on my browser this site appears (screenshot).
There is no possbility to create a new wallet!

![myetherwallet offline screenshot](https://github.com/MyEtherWallet/MyEtherWallet/assets/173482635/b28d73e1-41e4-4471-b0d6-fa526a8fc404)
###### Info

- **Version**:
- **Browser**: (Chrome/Firefox/Opera/etc..)
- **OS**: (Windows/Linux/Mac)
- **Page Url**: (ie https://myetherwallet.com/wallet/dashboard)

###### Steps to reproduce

A detailed list of reproduction steps.

###### What do you expect to happen?

...

###### What happens instead?

...

###### Screenshot

```
If you have some screenshots, please include them to the report
```
![myetherwallet offline screenshot](https://github.com/MyEtherWallet/MyEtherWallet/assets/173482635/fcbb1a4a-fe2b-48d9-b1f4-7f56158596f5)

**Comment by gamalielhere** [comment] 2024-07-30 18:00
Duplicate of #4947.

**Closed by gamalielhere** 2024-07-30 18:00 UTC
