### ISSUE TITLE
Refactor SendTransaction tab

### ISSUE THREAD

**Issue by HenryNguyen5** [MyEtherWallet/MyEtherWallet#205] opened 2017-09-18 04:58 UTC
Currently there's still a lot of transaction only functions inside the component itself that can be taken out, then re-used in other tabs like the ENS and Contracts tab

**Comment by dternyak** [comment] 2017-09-18 20:52
Duplicate of https://github.com/MyEtherWallet/MyEtherWallet/issues/142

**Comment by dternyak** [comment] 2017-09-18 20:53
I've assigned you to https://github.com/MyEtherWallet/MyEtherWallet/issues/142 instead :)

**Closed by dternyak** 2017-09-18 20:52 UTC
