### ISSUE TITLE
Persist wallet on tab change, auto-lock after timeout / allow manual lock

### ISSUE THREAD

**Issue by wbobeirne** [MyEtherWallet/MyEtherWallet#214] opened 2017-09-20 16:38 UTC
Split out from the somewhat oversized #80:

"Is having the wallet info disappear on each tab-change a feature? Would it be better if it persisted between tabs? (The only implication I can think of is how would a user "sign out" of their wallet so they could choose another one.)"

* 5(?) minutes -> show warning that their wallet is unlocked in the top tabby-guy (meta title tag)
* 30(?) minutes of no interaction -> lock wallet, force user to unlock again
* Make a little wallet icon with a cross through it or something that they can click to clear the current wallet from the current state and show the decrypt panel again

**Comment by wbobeirne** [comment] 2017-09-20 16:40
Personally I think we could go for some kind of a global unlock component, to get rid of the current (Kind of janky imo) behavior of that expanding / collapsing header. That could also potentially get rid of the view wallet tab, as you'd be able to look at your wallet on any tab without losing your current tab's state. I'd be happy to do a little ui exploration into this.

**Comment by tayvano** [comment] 2017-09-20 17:45
I  think the view wallet page can be nix'd. We just need a way for people to go unencrypted -> encrypted and re-print paper wallet (medium-term, low prio).

> Kind of janky imo

Understatement!

The only thing from a UX perspective that I would be careful about is any points in time where it may not make sense to keep the users state. I'm not sure what that would be, but perhaps when you send a transaction, navigate to the contracts tab, and then navigate back.

Do you want to see the details of your TX? Or be able to send another TX?

If see details, we should perhaps show details inline on page instead of in modal, lock inputs once it's been broadcast, and have a button to "send another tx". All little details though of what will ultimately be a better user experience globally .

**Comment by dternyak** [comment] 2017-10-03 05:02
I believe this is a duplicate of https://github.com/MyEtherWallet/MyEtherWallet/issues/197 -- I'll add this description to #197 and close this one.

**Comment by dternyak** [comment] 2017-10-03 05:02
On second thought, this one has additional discussion, so I'll close the other issue.

**Comment by dternyak** [comment] 2017-10-03 05:03
Description from #197 
```
Currently, MEW V3 will "log out" users after navigating away from Send.

When a user navigates away from Send, we should either prompt them to "log out" via a new dialog, or log out them out automatically.

"Log out" is defined as removing private key from state in the cases where we have it, and resetting sendTx View in all cases.
```

**Comment by james-prado** [comment] 2017-10-06 22:16
I created a working example [here](https://codesandbox.io/s/mywo0p1ppy), I just gotta implement it in the repo now and work out a few kinks.

**Closed** 2017-10-13 01:23 UTC
Labels: 0_issue: high, 2_wallet decrypt, blocking V4 full-launch, enhancement
