### ISSUE TITLE
Advanced Gas Limit Input Validation

### ISSUE THREAD

**Issue by dternyak** [MyEtherWallet/MyEtherWallet#840] opened 2018-01-15 22:27 UTC
- [x] Don't allow negative numbers
- [ ] Set upper-bound on gas limit (we can safely use the gas limit per block as the upper-bound).

**Comment by wbobeirne** [comment] 2018-01-15 22:30
Duplicate of #839

**Closed** 2018-01-21 18:41 UTC
Labels: 0_issue: high, blocking V4 full-launch
