### ISSUE TITLE
build error on darwin (webpack.prod.js)

### ISSUE THREAD

**Issue by Zwilla** [MyEtherWallet/MyEtherWallet#16] opened 2017-06-12 16:21 UTC
Hi, 
I got an error on compiling on my mac .
Tell the author that this fails on your system:
npm ERR!     webpack --config webpack_config/webpack.prod.js

***
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle MyEtherWallet@0.0.1~prebuild: MyEtherWallet@0.0.1
6 silly lifecycle MyEtherWallet@0.0.1~prebuild: no script for prebuild, continuing
7 info lifecycle MyEtherWallet@0.0.1~build: MyEtherWallet@0.0.1
8 verbose lifecycle MyEtherWallet@0.0.1~build: unsafe-perm in lifecycle true
9 verbose lifecycle MyEtherWallet@0.0.1~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Zwilla/IdeaProjects/MyEtherWallet-889765b89d58d130bad22ca4e0a9e58cd886eadb/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin
10 verbose lifecycle MyEtherWallet@0.0.1~build: CWD: /Users/Zwilla/IdeaProjects/MyEtherWallet-889765b89d58d130bad22ca4e0a9e58cd886eadb
11 silly lifecycle MyEtherWallet@0.0.1~build: Args: [ '-c', 'webpack --config webpack_config/webpack.prod.js' ]
12 silly lifecycle MyEtherWallet@0.0.1~build: Returned: code: 2  signal: null
13 info lifecycle MyEtherWallet@0.0.1~build: Failed to exec build script
14 verbose stack Error: MyEtherWallet@0.0.1 build: `webpack --config webpack_config/webpack.prod.js`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid MyEtherWallet@0.0.1
16 verbose cwd /Users/Zwilla/IdeaProjects/MyEtherWallet-889765b89d58d130bad22ca4e0a9e58cd886eadb
17 error Darwin 16.6.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
19 error node v6.10.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error MyEtherWallet@0.0.1 build: `webpack --config webpack_config/webpack.prod.js`
22 error Exit status 2
23 error Failed at the MyEtherWallet@0.0.1 build script 'webpack --config webpack_config/webpack.prod.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the MyEtherWallet package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack --config webpack_config/webpack.prod.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs MyEtherWallet
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls MyEtherWallet
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by crptm** [comment] 2017-06-12 21:07
there is nothing ready for production, so you probably the first who tried prod config :) Use npm start if you want to track progress.

**Comment by dternyak** [comment] 2017-08-16 22:13
@Zwilla Is this only on windows? It works fine for me on mac.

Due to a dependency issue with blockies, building the UI with webpack for prod isn't working. If you confirm its a windows issue, I'll rename the issue.

**Comment by Zwilla** [comment] 2017-08-16 22:50
long time ago… will test it the day’s again. But no I do not work on windoof since years

**Comment by dternyak** [comment] 2017-08-16 22:50
Ok -- I'm going to close it for now since I can't reproduce.

**Closed by dternyak** 2017-08-16 22:50 UTC
