### ISSUE TITLE
Going offline with any wallet presents Metamask / Mist no-send message

### ISSUE THREAD

**Issue by wbobeirne** [MyEtherWallet/MyEtherWallet#483] opened 2017-11-28 21:30 UTC
Got this message while testing offline with a private key wallet, looks like it's showing this no matter what maybe?

<img width="816" alt="screen shot 2017-11-28 at 12 31 25 pm" src="https://user-images.githubusercontent.com/649992/33342518-59b9e904-d450-11e7-8f8e-8b47c6292be8.png">

Assigning to @skubakdj since I think you worked on web3 wallets, but feel free to reassign if I'm wrong.

**Comment by dternyak** [comment] 2017-11-28 22:17
Duplicate of https://github.com/MyEtherWallet/MyEtherWallet/issues/391 (Which is already addressed in an outstanding PR)

**Closed by dternyak** 2017-11-28 22:17 UTC
Labels: 0_issue: med
