### ISSUE TITLE
Offline transaction signature is incorrect for transfer tokens

### ISSUE THREAD

**Issue by safonik** [MyEtherWallet/MyEtherWallet#4745] opened 2023-10-21 20:47 UTC
###### Info

- **Version**: 6.7.7-hotfix.2-Offline
- **Browser**: Chrome, Firefox
- **OS**: Any
- **Page Url**: index.html#/wallet/

###### Steps to reproduce
1. Export JSON file from "Send Offline Helper" (for BNB Smart Chain, but I think this bug is not network dependent)
2. Open index.html in a completely offline environment
3. Click on the button "Keystore files, Mnemonic phrase, Private key"
4. Enter private key
5. Upload JSON file, which was created in point 1
6. Choose token "BUSD"
7. Fill amount "1234"
8. Fill "To Address"
9. Click "Generate transaction"
10. Move signed transaction to online "Send Offline Helper" and try to send it
11. Get an error, because signature is invalid

**Comment by jm9151821** [comment] 2023-12-02 07:06
I am getting a similar error but the issue is with polygon. 

1.Export JSON file from "Send offline" ( for MATIC) from OFFLINE machine
2. Use "Send offline Helper" from MEW
3. select MATIC
4. set from Address
5. upload JSON file 
6. result in 'Incorrect network selected'

Thus cannot send matic tokens. It seems the offline helper from mew only works for Eth mainnet. Can anyone confirm or deny this please.

**Comment by gamalielhere** [comment] 2024-07-30 18:59
should be fixed on v6.9.8

**Closed by gamalielhere** 2024-07-30 18:59 UTC
