### ISSUE TITLE
tRIF token & contract address is wrong in RSK Testnet 

### ISSUE THREAD

**Issue by alepc253** [MyEtherWallet/MyEtherWallet#1467] opened 2019-10-02 20:45 UTC
- **I'm submitting a ...**

  - [ ] Feature request
  - [X] Bug report

This address is wrong: `0xd8c5adcac8d465c5a2d0772b86788e014ddec516` 
This address is the correct one: `0x19f64674d8a5b4e652319F5e239efd3bc969a1fe`

**Comment by gamalielhere** [comment] 2019-10-02 21:01
Will be fixed in the next release (5.1.6)

**Comment by alepc253** [comment] 2019-10-02 21:02
@gamalielhere where should we fix this now? I can't find the config file. Thanks!

**Comment by gamalielhere** [comment] 2019-10-02 21:03
@alepc253 for tokens, contracts, and darklist/whitelist issues: 
https://github.com/MyEtherWallet/ethereum-lists.

Regardless the issue is already fixed.
https://github.com/MyEtherWallet/ethereum-lists/commit/a0d1adbf100f86180e17cf4566e1ff2d8021424f

**Closed** 2019-10-10 19:02 UTC
Labels: Fixed

**Comment by alepc253** [comment] 2019-10-16 19:24
Hi @gamalielhere, I saw two problems:
- The address I passed has a uppercase `F` by mistake and it is rejected by web3, please change it to `0x19f64674d8a5b4e652319f5e239efd3bc969a1fe`
- I checked the change for the token address but it's missing in the `tRIF` preloaded contract

Thanks!

**Comment by gamalielhere** [comment] 2019-10-17 18:31
@alepc253 the last change wasn't included in the last release. It should be in the next upcoming release though.

**Comment by alepc253** [comment] 2019-10-17 20:06
@gamalielhere ok, I will check all again after the next release

**Comment by alepc253** [comment] 2019-11-19 15:47
@gamalielhere I still find the old address. The right one is `0x19F64674D8A5B4E652319F5e239eFd3bc969A1fE`.

<img width="802" alt="Captura de pantalla 2019-11-19 a la(s) 12 44 42" src="https://user-images.githubusercontent.com/3451282/69161945-a8ce8600-0aca-11ea-8e8c-8cdbd918d8cd.png">

**Comment by gamalielhere** [comment] 2019-11-19 19:18
@alepc253 My apologies, I forgot about the contract itself. It should be fixed on the next release. It's already fixed on [ethereum-lists](https://github.com/MyEtherWallet/ethereum-lists/commit/92ccc4b82f00029bd212151e62259f296778a670)
