### ISSUE TITLE
Help prevent phishing / spamming in MEW Slack

### ISSUE THREAD

**Issue by bmann** [MyEtherWallet/MyEtherWallet#28] opened 2017-07-04 01:07 UTC
Per Twitter discussion, let's use this thread to talk about solutions to help manage free community Slacks. 

Slack has a full API and a 3rd party tool could get built that helps with management.

**Comment by 409H** [comment] 2017-07-05 09:23
Although it won't be bulletproof, we could set up a directory of known e-mail addresses that are on the scammers addresses and autoblock them.

Then we could use [`reminders.list`](https://api.slack.com/methods/reminders.list) to fetch all the reminders on a channel, look to see if `reminders.creator` is in a whitelist (of admins or something), and then issue a [`reminders.delete`](https://api.slack.com/methods/reminders.delete) request of any reminder that wasn't created by an admin. This could be run every minute as a Slack App and manageable via a 3rd party site. 

I'm in favour of the last one as I think it would solve the immediate issues well - I mainly do PHP5.6 (occasionally PHP7) and would be happy to collab with someone. I'll start on that solution tonight and add the repo link here.

**Comment by tayvano** [comment] 2017-07-05 23:25
So alt.sq-3oxiaiy7@yopmail.com was one that was in our slack channel.....

**Comment by 409H** [comment] 2017-07-06 09:41
@tayvano perhaps we should auto-ban users with temporary e-mail addresses also

**Comment by 409H** [comment] 2017-07-06 09:50
### Proposed Solution

Create a Slack App for easy distribution to various teams to perform the following;

* Monitor signups and detect if a user has joined with a temporary/disposable e-mail address. Using [team_join](https://api.slack.com/events/team_join) event.
* Monitor messages triggered with `/remind` and delete them immediately if they were created by a non-admin/non-whitelisted user.
* Auto-delete/change any channel topic change that wasn't issued by a team admin. Relevant APIs/events:
 [channels.setTopic](https://api.slack.com/methods/channels.setTopic) and [channels.info](https://api.slack.com/methods/channels.info)

**Comment by tayvano** [comment] 2017-07-06 10:16
I think this is good plan. We have started a master list of known malicious addresses (fake ico links) and URLs...keeping that up to date and figuring out an easy way to push those updates live fast to slack bots or a chrome extension or whatever it may be (API?), I think we're In a better place. 

From there it's just a matter of making sure slacks use it, people use it, and there are easy ways for people to submit bad links / addresses to it. 

The latter is probably the easiest part of this.

**Comment by charlottefranklin** [comment] 2017-07-06 12:58
The issue we ran into is that an admin cannot delete any @slackbot IM channel reminders other than their own. We tested it on the API and had this confirmed by Slack.

**Comment by charlottefranklin** [comment] 2017-07-06 13:11
A bandaid we thought we could do is take a  look at writing an incoming webhook that triggers a slackbot response in a user's @slackbot IM channel when any reminders are posted there.

**Comment by 409H** [comment] 2017-07-06 13:14
With solo testing, I've got the app to remove reminders with the [`reminders.delete`](https://api.slack.com/methods/reminders.delete) method. When you did your testing, did you use webhooks or a slack app with the appropriate auth to each collection?

**Comment by charlottefranklin** [comment] 2017-07-06 13:23
We did it with 4 user accounts and sent various slackbot reminders to other users directly. We tested reminders.delete to query user slackbot IM channels - not public channels. We could not see or delete slackbot IMs that were not related to us, even as main admin. Slack confirmed it is not possible to delete other user's slackbot IMs, including reminders.

**Comment by altcoinio** [comment] 2017-07-06 14:08
The issue we ran into is that an admin cannot delete any @slackbot IM channel reminders other than their own. We tested it on the API by checking reminders.list for any slackbot IMs other than our own – and had this confirmed by Slack.

A bandaid we thought we could do is take a look at writing an incoming webhook that triggers a slackbot response in a user's @slackbot IM channel when any reminders are posted there.

We did it with 4 user accounts and sent various slackbot reminders to other users directly. We tested using reminders.delete to query the IDs of user slackbot IM channels - not public channels. We could not see, and therefore could not delete slackbot IMs that were not related to us, even as main admin. Slack confirmed it is not possible to delete other user's slackbot IMs, including reminders. They can only be deleted by the recipient or sender if sent as IM.

**Comment by altcoinio** [comment] 2017-07-06 14:15
But I have heard we can do this: You can add a bot who listens to slackbot DMs and deletes every message from him

**Comment by 409H** [comment] 2017-07-06 14:19
@altcoinio have you got a program in the works, or would you like me to push mine to the repo with slack app instructions/config for you to work off?

**Comment by altcoinio** [comment] 2017-07-06 17:40
Hi @409H - yes please if we can have look that would be great - are you using the node bot kit?

**Comment by 409H** [comment] 2017-07-07 07:57
@altcoinio Sorry, I was out last night, I'll commit and push later. No, a slack bot pointing to a PHP application.

**Comment by mikeyb** [comment] 2017-07-08 15:29
You all might want to check out MatterMost or RocketChat instead of slack.  Slack leaves you with very little power to control and stop things like this.  I am urging everyone to move away from slack to these free tools that enable us to run bigger communities without the insane hassle of dealing with these types of users.  If scammers know your self hosted chat server log everything they need to protect against said scammer, scammers will bother other chats that remain on slack.  Just my 2 cents

**Comment by altcoinio** [comment] 2017-07-08 16:23
Hey @mikeyb that was what we found too. I wrote our findings up here: https://medium.com/@altcoinio/slack-api-for-icos-de61df6448c3

**Comment by mikeyb** [comment] 2017-07-08 16:34
@altcoinio yes thanks!  I had just finished reading that a few minutes ago.  Thank you for the write up.  Seems like a silly attack vector Slack leaves available.  Still not sure why slack is used so much, it is the most unfriendly chat app I have ever seen for unpaid use (and not that great when paid for either)

**Comment by altcoinio** [comment] 2017-07-08 16:50
@mikeyb I'll add your suggestions for other chat tools at the bottom of the post - thank you.

**Comment by cleanforestco** [comment] 2017-09-20 07:23
Disabling the Slack API can prevent phishing attacks.
https://medium.com/@Paul__Walsh/how-to-disable-the-slack-api-to-prevent-phishing-attacks-inside-cryptocurrency-communities-4953d35db10c

**Comment by jet86** [comment] 2017-09-20 08:18
Disabling the Slack API only limits one small attack vector. It's definitely worth doing, but there's still plenty of phishing attacks happening in communities with the API already disabled.

**Comment by jet86** [comment] 2017-09-20 08:21
It may also be worth jumping into this thread if you're not already:
https://github.com/aragon/governance/issues/7

**Comment by 5chdn** [comment] 2017-09-20 08:32
@jet86 :+1: It's not worth to build fixes _around_ slack. It's probably more easy to totally abandon slack.

**Comment by jet86** [comment] 2017-09-20 08:35
That's exactly my point.

**Comment by dternyak** [comment] 2017-11-28 04:00
Closing due to staleness - happy to re-open should we need more discussion around this issue.

**Closed by dternyak** 2017-11-28 04:00 UTC
